import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";
import AppProvider from './components/AppContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppProvider>
        <Header />
        {children}
      </AppProvider>
        
      </body>
    </html>
  );
}
